DEBUG 2025-06-11 13:39:33.829 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 13:39:33.830 UTC: 	 Running on: Linux lx04.hep.ph.ic.ac.uk 5.14.0-503.33.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 19 16:23:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 13:39:33.830 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-06-11 13:39:33.830 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-11 13:39:33.830 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 13:39:33.830 UTC: 	 Found CRAB cache file /home/hep/jtafoyav/.crab3
ERROR 2025-06-11 13:39:33.831 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
ERROR 2025-06-11 13:39:33.832 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
INFO 2025-06-11 13:39:33.834 UTC: 	 Log file is /home/hep/jtafoyav/production_2023/tools/status_smarter/GENSIM/crab.log
DEBUG 2025-06-11 18:40:26.544 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 18:40:26.545 UTC: 	 Running on: Linux lx04.hep.ph.ic.ac.uk 5.14.0-503.33.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 19 16:23:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 18:40:26.545 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-06-11 18:40:26.545 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-11 18:40:26.545 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 18:40:26.545 UTC: 	 Found CRAB cache file /home/hep/jtafoyav/.crab3
ERROR 2025-06-11 18:40:26.547 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
ERROR 2025-06-11 18:40:26.547 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
INFO 2025-06-11 18:40:26.549 UTC: 	 Log file is /home/hep/jtafoyav/production_2023/tools/status_smarter/GENSIM/crab.log
DEBUG 2025-06-11 23:41:40.564 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 23:41:40.564 UTC: 	 Running on: Linux lx04.hep.ph.ic.ac.uk 5.14.0-503.33.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 19 16:23:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 23:41:40.564 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-06-11 23:41:40.564 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-11 23:41:40.564 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 23:41:40.565 UTC: 	 Found CRAB cache file /home/hep/jtafoyav/.crab3
ERROR 2025-06-11 23:41:40.567 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
ERROR 2025-06-11 23:41:40.567 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
INFO 2025-06-11 23:41:40.571 UTC: 	 Log file is /home/hep/jtafoyav/production_2023/tools/status_smarter/GENSIM/crab.log
DEBUG 2025-06-12 04:42:48.541 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-12 04:42:48.542 UTC: 	 Running on: Linux lx04.hep.ph.ic.ac.uk 5.14.0-503.33.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 19 16:23:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-12 04:42:48.542 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-06-12 04:42:48.542 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-12 04:42:48.542 UTC: 	 Executing command: 'status'
DEBUG 2025-06-12 04:42:48.543 UTC: 	 Found CRAB cache file /home/hep/jtafoyav/.crab3
ERROR 2025-06-12 04:42:48.545 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
ERROR 2025-06-12 04:42:48.545 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
INFO 2025-06-12 04:42:48.550 UTC: 	 Log file is /home/hep/jtafoyav/production_2023/tools/status_smarter/GENSIM/crab.log
DEBUG 2025-06-12 09:43:57.155 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-12 09:43:57.156 UTC: 	 Running on: Linux lx04.hep.ph.ic.ac.uk 5.14.0-503.33.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 19 16:23:31 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-12 09:43:57.156 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-06-12 09:43:57.156 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-12 09:43:57.156 UTC: 	 Executing command: 'status'
DEBUG 2025-06-12 09:43:57.157 UTC: 	 Found CRAB cache file /home/hep/jtafoyav/.crab3
ERROR 2025-06-12 09:43:57.159 UTC: 	 Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
ERROR 2025-06-12 09:43:57.160 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /home/hep/jtafoyav/production_2023/CMSSW_13_0_20/src/2023_GENSIM-v2_ext//scenarioB1_mpi_4_mA_0p67_ctau_10/crab_scenarioB1_mpi_4_mA_0p67_ctau_10/
INFO 2025-06-12 09:43:57.164 UTC: 	 Log file is /home/hep/jtafoyav/production_2023/tools/status_smarter/GENSIM/crab.log
